### ISSUE TITLE
Program programming

### ISSUE THREAD

**Issue by mozi-h** [wintergatan-community/virtual-mmx#5]
A user can input notes on a virtual programming wheel (38 channels 19 audio sources)

"Stiff" bass guitar frets (default notes only)

**Comment by mozi-h** [comment]
@Zakgriffin I need you to comment something here in order for me to assign this to you (GitHub won't allow assigning people randomly).

**Comment by Zakgriffin** [comment]
I would like to do this thing (please tell me I did it right this time)
