### ISSUE TITLE
GitHub Actions / Checks

### ISSUE THREAD

**Issue by mozi-h** [wintergatan-community/virtual-mmx#9]
- NPM:
  - [x] clean install
  - [x] build
  - [x] test
- [x] ~~pushing to master: update site branch with built react~~
- [x] Prettier, eslint checks
- [x] Docker

@mozi-h sturgelose

**Comment by Sturgelose** [comment]
@mozi-h willing to help here ;)

**Comment by xxfast** [comment]
Have experience with CI :)

**Comment by mozi-h** [comment]
I'll leave precedence to you two, as I have documentation and such to do for the repos (and final exams on Monday and Tuesday)

**Comment by wraybowling** [comment]
Is the plan to have this hosted via Github Pages? A live web page linked from the repo's URL field would be preferable.

**Comment by mozi-h** [comment]
Yeah, that’s the plan as if now, @wraybowling 
Will put it there, once we have the basics running

**Comment by mozi-h** [comment]
"pushing to master: update site branch with built react" moved to own issue #38
